'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.7905
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ESAR_Controls.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property active_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("active_search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bold16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bold16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CheckGroupBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckGroupBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property collapse_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("collapse_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property combobox_datetime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("combobox_datetime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property combobox_multi_column() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("combobox_multi_column", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property datagridview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("datagridview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DDContainer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DDContainer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eGroupBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eGroupBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eTabStrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eTabStrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property glass_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("glass_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradient_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient_panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_combobox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_combobox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inactive_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inactive_search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property italic16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italic16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property label() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("label", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property listcontrol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listcontrol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property listview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maskedtextbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maskedtextbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property people() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Picture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Picture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property progress_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progress_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RadioGroupBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RadioGroupBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restarrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restarrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property richtextbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("richtextbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rounded_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rounded_panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property searchtextbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("searchtextbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property selarrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selarrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property split_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("split_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starhotone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starhotone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property status_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tabcontrol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tabcontrol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property textaligncenter16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textaligncenter16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property textalignjustify16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textalignjustify16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property textalignleft16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textalignleft16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property textalignright16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textalignright16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property textbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("textbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property underline16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underline16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property varticallabel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("varticallabel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista_progress_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista_progress_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
